sources:
  - name: surgeswap-v2 # surgeswap-v1-eth
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/somemoecoding/surgeswap-v2 # https://api.thegraph.com/subgraphs/name/somemoecoding/surgeswap-v1-eth
documents:
  - ./example-query.graphql
